Repository ppp-team/my-petlog-server, pull requests merged in 2024-04, with the labels that each got.

#152 feat: add draft feature for diary
  petlog-api/src/main/java/com/ppp/api/diary/controller/DiaryDraftController.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/event/DiaryDraftUpdatedEvent.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/request/DiaryDraftCreateRequest.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryDetailResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryDraftCheckResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryDraftResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/exception/ErrorCode.java
  petlog-api/src/main/java/com/ppp/api/diary/handler/DiaryDraftEventHandler.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryDraftService.java
  petlog-api/src/test/java/com/ppp/ApiApplicationTests.java
  petlog-api/src/test/java/com/ppp/api/diary/controller/DiaryDraftControllerTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryDraftServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/common/constant/Domain.java
  petlog-domain/src/main/java/com/ppp/domain/diary/DiaryDraft.java
  petlog-domain/src/main/java/com/ppp/domain/diary/repository/DiaryDraftRedisRepository.java
Labels: feature

#158 feat: change authorization checks based on the division of diary into public/private
  petlog-api/src/main/java/com/ppp/api/diary/controller/DiaryFeedController.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryFeedResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryCommentService.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryFeedService.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryLikeService.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiarySearchService.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryService.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryCommentServiceTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryFeedServiceTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiarySearchServiceTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryServiceTest.java
  petlog-common/src/main/java/com/ppp/common/config/SecurityConfig.java
  petlog-domain/src/main/java/com/ppp/domain/diary/DiaryDocument.java
  petlog-domain/src/main/java/com/ppp/domain/diary/repository/DiaryCommentRepository.java
  petlog-domain/src/main/java/com/ppp/domain/diary/repository/DiaryQuerydslRepository.java
  petlog-domain/src/main/java/com/ppp/domain/diary/repository/DiaryRepository.java
  petlog-domain/src/main/java/com/ppp/domain/diary/repository/DiarySearchRepository.java
Labels: enhancement

#165 feat: modify findAllPageByReceiverId of notification
  petlog-api/src/main/java/com/ppp/api/notification/controller/NotificationController.java
  petlog-api/src/main/java/com/ppp/api/notification/service/NotificationService.java
  petlog-api/src/test/java/com/ppp/api/notification/service/NotificationServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/notification/Notification.java
  petlog-domain/src/main/java/com/ppp/domain/notification/repository/NotificationQuerydslRepository.java
Labels: bug, refactor, enhancement
