Repository ppp-team/my-petlog-server, pull requests merged in 2024-02, with the labels that each got.

#21 feat: build diary retrieval api endpoint
  petlog-api/src/main/java/com/ppp/api/diary/controller/DiaryController.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/request/DiaryRequest.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryDetailResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryGroupByDateResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryService.java
  petlog-api/src/main/java/com/ppp/api/user/dto/response/UserResponse.java
  petlog-api/src/main/resources/application-dev.yml
  petlog-api/src/main/resources/application-local.yml
  petlog-api/src/test/java/com/ppp/api/diary/controller/DiaryControllerTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/diary/repository/DiaryRepository.java
Labels: feature

#23 Bugfix/kjh/jasypt
  .gitignore
  petlog-common/src/main/java/com/ppp/common/config/JasyptConfig.java
Labels: bug

#24 feat: build diary comment create, update, delete api endpoint
  petlog-api/src/main/java/com/ppp/api/config/CacheConfig.java
  petlog-api/src/main/java/com/ppp/api/diary/controller/DiaryCommentController.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/request/DiaryCommentRequest.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryDetailResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryGroupByDateResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/exception/ErrorCode.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryCommentCountRedisService.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryCommentService.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryService.java
  petlog-api/src/test/java/com/ppp/ApiApplicationTests.java
  petlog-api/src/test/java/com/ppp/api/config/CacheIntegrationTest.java
  petlog-api/src/test/java/com/ppp/api/diary/controller/DiaryCommentControllerTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryCommentCountRedisServiceTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryCommentServiceTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryServiceTest.java
  petlog-api/src/test/java/com/ppp/api/test/TestConfig.java
  petlog-api/src/test/resources/application.yml
  petlog-common/src/main/java/com/ppp/common/client/RedisClient.java
  petlog-domain/build.gradle.kts
  petlog-domain/src/main/java/com/ppp/domain/common/constant/CacheValue.java
  petlog-domain/src/main/java/com/ppp/domain/common/constant/Domain.java
  petlog-domain/src/main/java/com/ppp/domain/diary/Diary.java
  petlog-domain/src/main/java/com/ppp/domain/diary/DiaryComment.java
  petlog-domain/src/main/java/com/ppp/domain/diary/DiaryMedia.java
  petlog-domain/src/main/java/com/ppp/domain/diary/repository/DiaryCommentRepository.java
Labels: feature

#28 feat: add the like feature
  petlog-api/src/main/java/com/ppp/api/config/CacheConfig.java
  petlog-api/src/main/java/com/ppp/api/diary/controller/DiaryCommentController.java
  petlog-api/src/main/java/com/ppp/api/diary/controller/DiaryController.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryCommentResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryDetailResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryCommentRedisService.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryCommentService.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryRedisService.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryService.java
  petlog-api/src/test/java/com/ppp/api/config/CacheIntegrationTest.java
  petlog-api/src/test/java/com/ppp/api/diary/controller/DiaryCommentControllerTest.java
  petlog-api/src/test/java/com/ppp/api/diary/controller/DiaryControllerTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryCommentRedisServiceIntegrationTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryCommentRedisServiceTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryCommentServiceTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryRedisServiceIntegrationTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/common/constant/CacheValue.java
  petlog-domain/src/main/java/com/ppp/domain/diary/repository/DiaryCommentRepository.java
  petlog-domain/src/main/java/com/ppp/domain/diary/repository/DiaryRepository.java
Labels: feature

#32 bugfix: 배포 에러 수정
  petlog-api/src/main/resources/application-dev.yml
Labels: bug

#37 feat: Setting up swagger and adding a response code #20
  petlog-api/src/main/java/com/ppp/api/auth/controller/AuthController.java
  petlog-api/src/main/java/com/ppp/api/auth/dto/request/RegisterRequest.java
  petlog-api/src/main/java/com/ppp/api/auth/service/AuthService.java
  petlog-api/src/main/java/com/ppp/api/config/SwaggerConfig.java
  petlog-api/src/main/java/com/ppp/api/user/controller/UserController.java
  petlog-api/src/main/java/com/ppp/api/user/dto/request/EmailRequest.java
  petlog-api/src/main/java/com/ppp/api/user/dto/request/NicknameRequest.java
  petlog-api/src/main/java/com/ppp/api/user/exception/ErrorCode.java
Labels: feature

#31 Create cicd.yml
  .github/workflows/cicd.yml
Labels: cicd

#42 refactor and test user api
  petlog-api/src/main/java/com/ppp/api/user/controller/UserController.java
  petlog-api/src/main/java/com/ppp/api/user/dto/response/ProfileResponse.java
  petlog-api/src/main/java/com/ppp/api/user/service/UserService.java
  petlog-api/src/test/java/com/ppp/api/auth/controller/AuthControllerTest.java
  petlog-api/src/test/java/com/ppp/api/auth/service/AuthServiceTest.java
  petlog-api/src/test/java/com/ppp/api/user/controller/UserControllerTest.java
  petlog-api/src/test/java/com/ppp/api/user/service/UserServiceTest.java
Labels: refactor

#47 fix: modify to ensure that the file path does not start with / during creation
  petlog-common/src/main/java/com/ppp/common/util/FilePathUtil.java
  petlog-common/src/test/java/com/ppp/common/util/FilePathUtilTest.java
Labels: bug

#44 feat: build diary search api endpoint
  petlog-api/build.gradle.kts
  petlog-api/src/main/java/com/ppp/api/config/AsyncConfig.java
  petlog-api/src/main/java/com/ppp/api/diary/controller/DiarySearchController.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/event/DiaryCommentCreatedEvent.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/event/DiaryCommentDeletedEvent.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/event/DiaryCreatedEvent.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/event/DiaryDeletedEvent.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/event/DiaryUpdatedEvent.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryGroupByDateResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/handler/DiaryCommentEventHandler.java
  petlog-api/src/main/java/com/ppp/api/diary/handler/DiaryEventHandler.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryCommentService.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiarySearchService.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryService.java
  petlog-api/src/main/java/com/ppp/api/user/dto/response/UserResponse.java
  petlog-api/src/main/resources/application-dev.yml
  petlog-api/src/main/resources/application-local.yml
  petlog-api/src/test/java/com/ppp/api/diary/controller/DiarySearchControllerTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryCommentServiceTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiarySearchServiceTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryServiceTest.java
  petlog-api/src/test/java/com/ppp/api/log/service/LogServiceTest.java
  petlog-common/build.gradle.kts
  petlog-common/src/main/java/com/ppp/common/client/ElasticSearchClient.java
  petlog-domain/build.gradle.kts
  petlog-domain/src/main/java/com/ppp/domain/common/BaseDocument.java
  petlog-domain/src/main/java/com/ppp/domain/diary/Diary.java
  petlog-domain/src/main/java/com/ppp/domain/diary/DiaryDocument.java
  petlog-domain/src/main/java/com/ppp/domain/diary/repository/DiarySearchRepository.java
  petlog-domain/src/main/java/com/ppp/domain/user/UserDocument.java
Labels: feature

#52 fix: fix the bug that the webserver cannot connect with the elastic search
  .github/workflows/cicd.yml
Labels: bug, cicd

#55 feat: add my-pets api
  petlog-api/src/main/java/com/ppp/api/auth/exception/ErrorCode.java
  petlog-api/src/main/java/com/ppp/api/pet/controller/PetsController.java
  petlog-api/src/main/java/com/ppp/api/pet/dto/request/PetRequest.java
  petlog-api/src/main/java/com/ppp/api/pet/dto/response/MyPetResponse.java
  petlog-api/src/main/java/com/ppp/api/pet/dto/response/MyPetsResponse.java
  petlog-api/src/main/java/com/ppp/api/pet/exception/ErrorCode.java
  petlog-api/src/main/java/com/ppp/api/pet/service/PetsService.java
  petlog-api/src/main/java/com/ppp/api/user/controller/UserController.java
  petlog-api/src/main/java/com/ppp/api/user/dto/request/EmailRequest.java
  petlog-api/src/main/java/com/ppp/api/user/dto/request/NicknameRequest.java
  petlog-api/src/test/java/com/ppp/api/pet/controller/PetsControllerTest.java
  petlog-api/src/test/java/com/ppp/api/pet/service/PetsServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/common/constant/Domain.java
  petlog-domain/src/main/java/com/ppp/domain/pet/Pet.java
  petlog-domain/src/main/java/com/ppp/domain/pet/PetImage.java
  petlog-domain/src/main/java/com/ppp/domain/pet/constant/Gender.java
  petlog-domain/src/main/java/com/ppp/domain/pet/constant/RepStatus.java
  petlog-domain/src/main/java/com/ppp/domain/pet/repository/PetImageRepository.java
  petlog-domain/src/main/java/com/ppp/domain/pet/repository/PetRepository.java
Labels: feature

#60 hotfix: fix the bug that the web server failed to start
  .github/workflows/cicd.yml
Labels: bug, cicd

#58 feat: apply pagination to diary comment retrieval api
  petlog-api/src/main/java/com/ppp/api/diary/controller/DiaryCommentController.java
  petlog-api/src/main/java/com/ppp/api/diary/controller/DiaryController.java
  petlog-api/src/main/java/com/ppp/api/diary/controller/DiarySearchController.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryCommentResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryDetailResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryGroupByDateResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryCommentService.java
  petlog-api/src/main/java/com/ppp/api/log/dto/request/LogRequest.java
  petlog-api/src/main/java/com/ppp/api/log/service/LogService.java
  petlog-api/src/main/java/com/ppp/api/pet/dto/response/PetResponse.java
  petlog-api/src/main/java/com/ppp/api/user/dto/response/UserResponse.java
  petlog-api/src/test/java/com/ppp/api/diary/controller/DiaryCommentControllerTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryCommentServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/diary/repository/DiaryCommentRepository.java
Labels: documentation, feature

#62 feat: Add 관리(my) API
  petlog-api/src/main/java/com/ppp/api/exception/GlobalExceptionHandler.java
  petlog-api/src/main/java/com/ppp/api/guardian/controller/GuardianController.java
  petlog-api/src/main/java/com/ppp/api/guardian/dto/request/DeleteGuardianRequest.java
  petlog-api/src/main/java/com/ppp/api/guardian/dto/request/InviteGuardianRequest.java
  petlog-api/src/main/java/com/ppp/api/guardian/dto/response/GuardianResponse.java
  petlog-api/src/main/java/com/ppp/api/guardian/dto/response/GuardiansResponse.java
  petlog-api/src/main/java/com/ppp/api/guardian/exception/ErrorCode.java
  petlog-api/src/main/java/com/ppp/api/guardian/exception/GuardianException.java
  petlog-api/src/main/java/com/ppp/api/guardian/service/GuardianService.java
  petlog-api/src/main/java/com/ppp/api/invitation/controller/InvitationController.java
  petlog-api/src/main/java/com/ppp/api/invitation/dto/request/InvitationRequest.java
  petlog-api/src/main/java/com/ppp/api/invitation/dto/response/InvitationResponse.java
  petlog-api/src/main/java/com/ppp/api/invitation/exception/ErrorCode.java
  petlog-api/src/main/java/com/ppp/api/invitation/exception/InvitationException.java
  petlog-api/src/main/java/com/ppp/api/invitation/service/InvitationService.java
  petlog-api/src/main/java/com/ppp/api/pet/controller/PetController.java
  petlog-api/src/main/java/com/ppp/api/pet/service/PetService.java
  petlog-api/src/test/java/com/ppp/api/pet/controller/PetControllerTest.java
  petlog-api/src/test/java/com/ppp/api/pet/service/PetServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/guardian/repository/GuardianRepository.java
  petlog-domain/src/main/java/com/ppp/domain/invitation/Invitation.java
  petlog-domain/src/main/java/com/ppp/domain/invitation/constant/InviteStatus.java
  petlog-domain/src/main/java/com/ppp/domain/invitation/repository/InvitationRepository.java
  petlog-domain/src/main/java/com/ppp/domain/user/User.java
Labels: feature

#65 fix: add multipart form request
  petlog-api/src/main/java/com/ppp/api/pet/controller/PetController.java
  petlog-api/src/main/java/com/ppp/api/pet/dto/request/PetRequest.java
  petlog-api/src/main/java/com/ppp/api/user/controller/UserController.java
  petlog-api/src/main/java/com/ppp/api/user/service/UserService.java
Labels: bug

#66 feat: apply feature about video on diary apis
  .github/workflows/cicd.yml
  petlog-api/src/main/java/com/ppp/api/diary/controller/DiaryController.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/request/DiaryCreateRequest.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/request/DiaryUpdateRequest.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryDetailResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryMediaResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/exception/ErrorCode.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryService.java
  petlog-api/src/main/java/com/ppp/api/video/controller/VideoController.java
  petlog-api/src/main/java/com/ppp/api/video/dto/response/VideoResponse.java
  petlog-api/src/main/java/com/ppp/api/video/exception/ErrorCode.java
  petlog-api/src/test/java/com/ppp/api/diary/controller/DiaryControllerTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryServiceTest.java
  petlog-common/src/main/java/com/ppp/common/client/FileStorageClient.java
  petlog-common/src/main/java/com/ppp/common/client/S3Client.java
  petlog-common/src/main/java/com/ppp/common/service/FileStorageManageService.java
  petlog-common/src/test/java/com/ppp/common/service/FileStorageManageServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/diary/Diary.java
  petlog-domain/src/main/java/com/ppp/domain/diary/constant/DiaryPolicy.java
Labels: feature

#70 Update cicd.yml
  .github/workflows/cicd.yml
Labels: cicd

#72 fix: add locale configuration in JsonFormat
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryGroupByDateResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryService.java
  petlog-api/src/main/java/com/ppp/api/log/dto/response/LogGroupByDateResponse.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryServiceTest.java
  petlog-api/src/test/resources/application.yml
  petlog-domain/src/main/java/com/ppp/domain/diary/Diary.java
  petlog-domain/src/main/java/com/ppp/domain/diary/repository/DiaryRepository.java
Labels: bug

#75 chore: add user profile path field about diary response
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/handler/DiaryCommentEventHandler.java
  petlog-api/src/main/java/com/ppp/api/diary/handler/DiaryEventHandler.java
  petlog-api/src/main/java/com/ppp/api/user/dto/response/UserResponse.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryCommentServiceTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/user/User.java
Labels: refactor

#76 feat: add pet's guardians retrieval api for log, diary comment
  petlog-api/src/main/java/com/ppp/api/guardian/controller/GuardianController.java
  petlog-api/src/main/java/com/ppp/api/guardian/exception/ErrorCode.java
  petlog-api/src/main/java/com/ppp/api/guardian/service/GuardianService.java
  petlog-api/src/main/java/com/ppp/api/user/dto/response/UserResponse.java
  petlog-api/src/test/java/com/ppp/api/guardian/controller/GuardianControllerTest.java
  petlog-api/src/test/java/com/ppp/api/guardian/service/GuardianServiceTest.java
  petlog-domain/build.gradle.kts
  petlog-domain/src/main/java/com/ppp/domain/common/config/QuerydslConfig.java
  petlog-domain/src/main/java/com/ppp/domain/user/UserDao.java
  petlog-domain/src/main/java/com/ppp/domain/user/repository/UserQuerydslRepository.java
Labels: feature, config

#77 chore: modify code in response to feedback
  petlog-api/src/main/java/com/ppp/api/guardian/controller/GuardianController.java
  petlog-api/src/main/java/com/ppp/api/guardian/service/GuardianService.java
  petlog-api/src/main/java/com/ppp/api/invitation/controller/InvitationController.java
  petlog-api/src/main/java/com/ppp/api/invitation/dto/response/MyInvitationResponse.java
  petlog-api/src/main/java/com/ppp/api/invitation/service/InvitationService.java
Labels: refactor

#80 feat: build api to retrieve days of log recorded by the month
  petlog-api/src/main/java/com/ppp/api/log/controller/LogController.java
  petlog-api/src/main/java/com/ppp/api/log/dto/response/LogCalenderResponse.java
  petlog-api/src/main/java/com/ppp/api/log/service/LogService.java
  petlog-api/src/test/java/com/ppp/api/log/controller/LogControllerTest.java
  petlog-api/src/test/java/com/ppp/api/log/service/LogServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/diary/constant/DiaryPolicy.java
  petlog-domain/src/main/java/com/ppp/domain/log/repository/LogQuerydslRepository.java
  petlog-domain/src/main/java/com/ppp/domain/user/repository/UserQuerydslRepository.java
Labels: feature

#84 fix: fix the log delete bug that was caused by loading non existed log location
  petlog-api/src/main/java/com/ppp/api/log/service/LogService.java
  petlog-common/src/main/java/com/ppp/common/service/FileStorageManageService.java
  petlog-domain/src/main/java/com/ppp/domain/log/Log.java
Labels: bug

#87 fix: change relationship between log and log location
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryService.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryServiceTest.java
  petlog-api/src/test/java/com/ppp/api/log/service/LogServiceTest.java
  petlog-common/src/main/java/com/ppp/common/service/ThumbnailService.java
  petlog-common/src/test/java/com/ppp/common/service/ThumbnailServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/log/Log.java
  petlog-domain/src/main/java/com/ppp/domain/log/LogLocation.java
  petlog-domain/src/main/java/com/ppp/domain/log/repository/LogLocationRepository.java
Labels: bug

#88 feat: Add login api #79
  petlog-api/src/main/java/com/ppp/api/auth/controller/AuthController.java
  petlog-api/src/main/java/com/ppp/api/auth/dto/request/RegisterRequest.java
  petlog-api/src/main/java/com/ppp/api/auth/dto/request/SigninRequest.java
  petlog-api/src/main/java/com/ppp/api/auth/dto/request/SocialRequest.java
  petlog-api/src/main/java/com/ppp/api/auth/service/AuthService.java
  petlog-domain/src/main/java/com/ppp/domain/user/User.java
Labels: feature

#85 Update cicd.yml
  .github/workflows/cicd.yml
Labels: cicd

#86 feat: Add validate password api
  petlog-api/src/main/java/com/ppp/api/auth/exception/ErrorCode.java
  petlog-api/src/main/java/com/ppp/api/user/controller/UserController.java
  petlog-api/src/main/java/com/ppp/api/user/dto/request/ValidatePasswordRequest.java
  petlog-api/src/main/java/com/ppp/api/user/service/UserService.java
Labels: feature

#89 bugfix: isNeutered allows null
  petlog-api/src/main/java/com/ppp/api/pet/dto/response/MyPetResponse.java
  petlog-api/src/main/java/com/ppp/api/pet/service/PetService.java
Labels: bug

#90 fix: change log response format according to the requirement
  petlog-api/src/main/java/com/ppp/api/log/dto/response/LogDetailResponse.java
  petlog-api/src/main/java/com/ppp/api/log/dto/response/LogResponse.java
  petlog-api/src/main/java/com/ppp/api/log/service/LogService.java
  petlog-api/src/test/java/com/ppp/api/log/service/LogServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/log/Log.java
  petlog-domain/src/main/java/com/ppp/domain/log/LogLocation.java
  petlog-domain/src/main/java/com/ppp/domain/log/repository/LogLocationRepository.java
  petlog-domain/src/main/java/com/ppp/domain/log/repository/LogRepository.java
  petlog-domain/src/main/java/com/ppp/domain/user/repository/UserRepository.java
Labels: feature, refactor

#93 fix: modify diary comment keys used in redis more detailed
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryCommentRedisService.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryRedisService.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryCommentRedisServiceIntegrationTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryRedisServiceIntegrationTest.java
  petlog-domain/src/main/java/com/ppp/domain/common/constant/Domain.java
Labels: bug

#95 feat: apply to updated user profile in diary search
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryCommentRedisService.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiarySearchService.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryService.java
  petlog-api/src/main/java/com/ppp/api/user/dto/event/UserProfileUpdatedEvent.java
  petlog-api/src/main/java/com/ppp/api/user/handler/UserEventHandler.java
  petlog-api/src/main/java/com/ppp/api/user/service/UserService.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiarySearchServiceTest.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryServiceTest.java
  petlog-api/src/test/java/com/ppp/api/user/service/UserServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/diary/DiaryDocument.java
  petlog-domain/src/main/java/com/ppp/domain/diary/repository/DiarySearchRepository.java
Labels: feature

#98 fix: updating profileImage allows null
  petlog-api/src/main/java/com/ppp/api/user/service/UserService.java
  petlog-domain/src/main/java/com/ppp/domain/user/User.java
Labels: feature

#100 query optimization using joining
  petlog-api/src/main/java/com/ppp/api/diary/controller/DiaryCommentController.java
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryCommentResponse.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryCommentService.java
  petlog-api/src/main/java/com/ppp/api/diary/service/DiaryService.java
  petlog-api/src/main/java/com/ppp/api/log/service/LogService.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiaryCommentServiceTest.java
  petlog-api/src/test/java/com/ppp/api/log/service/LogServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/diary/Diary.java
  petlog-domain/src/main/java/com/ppp/domain/diary/repository/DiaryCommentRepository.java
  petlog-domain/src/main/java/com/ppp/domain/diary/repository/DiaryRepository.java
  petlog-domain/src/main/java/com/ppp/domain/log/Log.java
  petlog-domain/src/main/java/com/ppp/domain/log/repository/LogRepository.java
  petlog-domain/src/main/java/com/ppp/domain/user/repository/UserRepository.java
Labels: refactor, enhancement

#102 feat: modify two mypet APIs
  petlog-api/src/main/java/com/ppp/api/guardian/service/GuardianService.java
  petlog-api/src/main/java/com/ppp/api/invitation/controller/InvitationController.java
  petlog-api/src/main/java/com/ppp/api/invitation/service/InvitationService.java
  petlog-api/src/main/java/com/ppp/api/pet/controller/PetController.java
  petlog-api/src/main/java/com/ppp/api/pet/dto/response/MyPetResponse.java
  petlog-api/src/main/java/com/ppp/api/pet/service/PetService.java
  petlog-api/src/test/java/com/ppp/api/config/CacheIntegrationTest.java
  petlog-api/src/test/java/com/ppp/api/guardian/service/GuardianServiceTest.java
  petlog-api/src/test/java/com/ppp/api/pet/controller/PetControllerTest.java
  petlog-api/src/test/java/com/ppp/api/pet/service/PetServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/guardian/Guardian.java
  petlog-domain/src/main/java/com/ppp/domain/guardian/dto/MyPetResponseDto.java
  petlog-domain/src/main/java/com/ppp/domain/guardian/repository/GuardianQuerydslRepository.java
  petlog-domain/src/main/java/com/ppp/domain/invitation/repository/InvitationQuerydslRepository.java
Labels: feature

#103 feat : add updating image
  petlog-api/src/main/java/com/ppp/api/user/controller/UserController.java
  petlog-api/src/main/java/com/ppp/api/user/service/UserService.java
  petlog-api/src/test/java/com/ppp/api/user/service/UserServiceTest.java
Labels: feature

#105 fix: fix the bug that diary search result's page info is incorrect
  petlog-api/src/main/java/com/ppp/api/diary/service/DiarySearchService.java
  petlog-api/src/main/java/com/ppp/api/pet/service/PetService.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiarySearchServiceTest.java
  petlog-api/src/test/java/com/ppp/api/guardian/controller/GuardianControllerTest.java
  petlog-common/src/main/java/com/ppp/common/config/SecurityConfig.java
  petlog-domain/src/main/java/com/ppp/domain/common/util/GenerationUtil.java
  petlog-domain/src/main/java/com/ppp/domain/diary/Diary.java
  petlog-domain/src/main/java/com/ppp/domain/guardian/repository/GuardianRepository.java
  petlog-domain/src/main/java/com/ppp/domain/user/User.java
Labels: bug

#104 chore: correct the event logic written incorrectly
  petlog-api/src/main/java/com/ppp/api/user/service/UserService.java
Labels: refactor

#106 fix: resolve the branch conflict by refactoring on diary
  petlog-domain/src/main/java/com/ppp/domain/diary/Diary.java
Labels: refactor

#109 bugfix : fix selecting representative pet and deleting pet
  petlog-api/src/main/java/com/ppp/api/guardian/controller/GuardianController.java
  petlog-api/src/main/java/com/ppp/api/guardian/service/GuardianService.java
  petlog-api/src/main/java/com/ppp/api/pet/controller/PetController.java
  petlog-api/src/main/java/com/ppp/api/pet/dto/response/MyPetResponse.java
  petlog-api/src/main/java/com/ppp/api/pet/service/PetService.java
  petlog-api/src/test/java/com/ppp/api/guardian/service/GuardianServiceTest.java
  petlog-api/src/test/java/com/ppp/api/pet/service/PetServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/guardian/Guardian.java
  petlog-domain/src/main/java/com/ppp/domain/guardian/constant/RepStatus.java
  petlog-domain/src/main/java/com/ppp/domain/guardian/repository/GuardianQuerydslRepository.java
  petlog-domain/src/main/java/com/ppp/domain/guardian/repository/GuardianRepository.java
  petlog-domain/src/main/java/com/ppp/domain/pet/Pet.java
  petlog-domain/src/main/java/com/ppp/domain/pet/repository/PetRepository.java
Labels: bug

#110 fix : modify findMyPet Query #108
  petlog-api/src/main/java/com/ppp/api/auth/controller/AuthController.java
  petlog-api/src/main/java/com/ppp/api/auth/service/AuthService.java
  petlog-api/src/main/java/com/ppp/api/pet/dto/response/MyPetResponse.java
  petlog-common/src/main/java/com/ppp/common/config/SecurityConfig.java
  petlog-domain/src/main/java/com/ppp/domain/guardian/dto/MyPetResponseDto.java
  petlog-domain/src/main/java/com/ppp/domain/guardian/repository/GuardianQuerydslRepository.java
Labels: bug

#111 fix : modify findMyPet query
  petlog-api/src/main/java/com/ppp/api/pet/controller/PetController.java
  petlog-api/src/main/java/com/ppp/api/pet/dto/response/MyPetResponse.java
  petlog-api/src/main/java/com/ppp/api/pet/service/PetService.java
  petlog-api/src/test/java/com/ppp/api/pet/service/PetServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/guardian/dto/MyPetDto.java
  petlog-domain/src/main/java/com/ppp/domain/guardian/repository/GuardianQuerydslRepository.java
Labels: bug

#112 fix : fix guardian and pet issue
  petlog-api/src/main/java/com/ppp/api/guardian/controller/GuardianController.java
  petlog-api/src/main/java/com/ppp/api/guardian/service/GuardianService.java
  petlog-api/src/main/java/com/ppp/api/invitation/service/InvitationService.java
  petlog-api/src/main/java/com/ppp/api/pet/controller/PetController.java
  petlog-api/src/main/java/com/ppp/api/pet/service/PetService.java
  petlog-api/src/test/java/com/ppp/api/guardian/service/GuardianServiceTest.java
  petlog-api/src/test/java/com/ppp/api/pet/service/PetServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/guardian/repository/GuardianQuerydslRepository.java
  petlog-domain/src/main/java/com/ppp/domain/guardian/repository/GuardianRepository.java
  petlog-domain/src/main/java/com/ppp/domain/pet/repository/PetRepository.java
Labels: bug, refactor

#115 feat: modify update pet
  petlog-api/src/main/java/com/ppp/api/guardian/service/GuardianService.java
  petlog-api/src/main/java/com/ppp/api/invitation/controller/InvitationController.java
  petlog-api/src/main/java/com/ppp/api/invitation/dto/response/MyInvitationResponse.java
  petlog-api/src/main/java/com/ppp/api/invitation/service/InvitationService.java
  petlog-api/src/test/java/com/ppp/api/guardian/service/GuardianServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/invitation/repository/InvitationRepository.java
  petlog-domain/src/main/java/com/ppp/domain/pet/Pet.java
Labels: feature, refactor

#119 fix: change ffmpeg command taking into account the aspect ratio
  petlog-common/src/main/java/com/ppp/common/client/FfmpegClient.java
  petlog-domain/src/main/java/com/ppp/domain/common/constant/VideoCompressType.java
Labels: bug

#117 fix: modify cached data when guardian is deleted
  petlog-api/src/main/java/com/ppp/api/guardian/service/GuardianService.java
  petlog-api/src/main/java/com/ppp/api/pet/service/PetService.java
  petlog-api/src/test/java/com/ppp/api/config/CacheIntegrationTest.java
  petlog-api/src/test/java/com/ppp/api/guardian/service/GuardianServiceTest.java
  petlog-api/src/test/java/com/ppp/api/pet/service/PetServiceTest.java
  petlog-common/src/main/java/com/ppp/common/service/CacheManageService.java
  petlog-domain/src/main/java/com/ppp/domain/guardian/repository/GuardianRepository.java
Labels: bug, enhancement

#120 fix: modify validation condition
  petlog-api/src/main/java/com/ppp/api/guardian/controller/GuardianController.java
  petlog-api/src/main/java/com/ppp/api/guardian/exception/ErrorCode.java
  petlog-api/src/main/java/com/ppp/api/guardian/service/GuardianService.java
  petlog-api/src/test/java/com/ppp/api/guardian/service/GuardianServiceTest.java
Labels: bug

#122 fix: change ffmpeg command to truncate decimals
  petlog-common/src/main/java/com/ppp/common/client/FfmpegClient.java
Labels: bug

#129 fix: limit aggregated terms size and change min document threshold
  petlog-api/src/main/java/com/ppp/api/diary/dto/response/DiaryMostUsedTermsResponse.java
  petlog-api/src/test/java/com/ppp/api/diary/service/DiarySearchServiceTest.java
  petlog-domain/src/main/java/com/ppp/domain/diary/dto/DiaryMostUsedTermsDto.java
  petlog-domain/src/main/java/com/ppp/domain/diary/repository/DiarySearchQuerydslRepository.java
Labels: feature, refactor

#130 fix : modify update Pet api
  petlog-api/src/main/java/com/ppp/api/pet/service/PetService.java
Labels: bug
